development:
  adapter: mysql2
  encoding: utf8
  database: emp_development
  username: root
  password: root
  host: 2.4.1
  port: 3306
test:
  adapter: mysql2
  encoding: utf8
  database: emp_test
  username: root
  password: root
  host: 2.4.1
  port: 3306
production:
  adapter: mysql2
  encoding: utf8
  database: emp_production
  username: root
  password: root
  host: 2.4.1
  port: 3306
